# Generated by Django 2.1.7 on 2019-02-22 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0002_auto_20190221_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='managers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
