# Generated by Django 2.1.7 on 2019-02-22 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_market_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='managers',
            field=models.ManyToManyField(related_name='markets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='market',
            name='shops',
            field=models.ManyToManyField(related_name='markets', to='markets.Shop'),
        ),
    ]
